Add translation string for Play Youtube Video button aria-label
wp-media/rocket-lazyload-common pull request #122
Opened 2024-12-24 11:15 UTC by audrasjb

# Description

See this issue on WP-Rocket: https://github.com/wp-media/wp-rocket/issues/7202
And the following PR: https://github.com/wp-media/wp-rocket/pull/7203

## Type of change

- [ ] New feature (non-breaking change which adds functionality).
- [x] Bug fix (non-breaking change which fixes an issue).
- [ ] Enhancement (non-breaking change which improves an existing functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as before).
- [ ] Sub-task of #(issue number)
- [ ] Chore
- [ ] Release

## Detailed scenario

See https://github.com/wp-media/wp-rocket/pull/7203

## Technical description

See https://github.com/wp-media/wp-rocket/pull/7203

### Documentation

See https://github.com/wp-media/wp-rocket/pull/7203

### New dependencies

None

### Risks

None

# Mandatory Checklist

## Code validation

- [x] I validated all the Acceptance Criteria. If possible, provide screenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [x] I implemented built-in tests to cover the new/changed code.

## Code style

- [x] I wrote a self-explanatory code about what it does.
- [x] I protected entry points against unexpected inputs.
- [x] I did not introduce unnecessary complexity.
- [x] Output messages (errors, notices, logs) are explicit enough for users to understand the issue and are actionnable.

# Additional Checks
- [x] In the case of complex code, I wrote comments to explain it.
- [x] When possible, I prepared ways to observe the implemented system (logs, data, etc.).
- [x] I added error handling logic when using functions that could throw errors (HTTP/API request, filesystem, etc.)

2024-12-24 11:21 UTC, audrasjb commented
My only concern is the gettext string text-domain.
I used the slug of this library as text-domain but this implies that any project using this library will have to change the related text-domain accordingly. I didn't find any other user facing string in this library.

Another option would be to replace the gettext translation string with a filter that could be used by other projects to replace the string with a gettext translation string.

What do you think?

2025-01-14 08:31 UTC, wordpressfan requested changes
Sorry for being late here, Happy new year.
Just a small change request/question.

2025-01-14 08:31 UTC, wordpressfan commented on src/Assets.php
> +		$button_aria_label = esc_attr__( 'play Youtube video', 'rocket-lazyload-common' );
What if we passed this to $args array? and here we add the fallback to that string.
This will solve the translations issue and keep the current functionality as is for anyone that uses this library.

What do u think?

2025-01-14 08:40 UTC, audrasjb commented on src/Assets.php
> +		$button_aria_label = esc_attr__( 'play Youtube video', 'rocket-lazyload-common' );
yeah, looks like a good alternative too.

2025-01-14 08:43 UTC, audrasjb commented on src/Assets.php
> +		$button_aria_label = esc_attr__( 'play Youtube video', 'rocket-lazyload-common' );
done

2025-01-21 16:50 UTC, wordpressfan commented
Many thanks @audrasjb 
I'm going to merge this and create another PR to fix svn in tests workflow then move forward from there.

2025-01-21 16:51 UTC, merged